version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: pg_local_restaurant
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: restaurant_db
      TZ: "UTC"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/restaurant_data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d restaurant_db"]
      interval: 5s
      timeout: 3s
      retries: 10
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_restaurant
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: app@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: app
    volumes:
      - pgadmin-data:/var/lib/pgadmin_restaurant

volumes:
  pgdata:
  pgadmin-data: